- name: reload systemd
  when: not ansible_check_mode
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart chrony
  when: not ansible_check_mode
  ansible.builtin.systemd:
    name: chrony
    state: restarted

- name: restart docker
  when: not ansible_check_mode
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: restart systemd-modules-load
  when: not ansible_check_mode
  ansible.builtin.systemd:
    name: systemd-modules-load
    state: restarted

- name: restart cri-docker
  when: not ansible_check_mode
  ansible.builtin.systemd:
    name: cri-docker
    state: restarted

- name: apply sysctl
  when: not ansible_check_mode
  ansible.builtin.command: sysctl --system
  changed_when: false


